Document: tpbuff
Title: Debian tpbuff Manual
Author: <insert document author here>
Abstract: This manual describes what tpbuff is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/tpbuff/tpbuff.sgml.gz

Format: postscript
Files: /usr/share/doc/tpbuff/tpbuff.ps.gz

Format: text
Files: /usr/share/doc/tpbuff/tpbuff.text.gz

Format: HTML
Index: /usr/share/doc/tpbuff/html/index.html
Files: /usr/share/doc/tpbuff/html/*.html
